name: Deploy Stage Android CI

on:
  release:
    types: prereleased

jobs:
  android:
    if: contains(github.ref, 'android_')
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.event.release.target_commitish }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: extract keystore
      env: 
        KEYSTORE: ${{ secrets.KEYSTORE }}
      run: echo $KEYSTORE | base64 --decode > ./app/keystore.jks
    - name: extract keystore properties
      env:
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      run: echo "$KEYSTORE_PROPERTIES" > ./app/keystore.properties
    - name: extract supply key
      env:
        SUPPLY_KEY: ${{ secrets.PLAYSTORE_DREIPOL }}
      run: echo "$SUPPLY_KEY" > ./app/fastlane/supplyKey.json
    - name: setup ruby version
      uses: actions/setup-ruby@v1
      with: 
        ruby-version: '2.6'
    - name: install bundler
      run: gem install bundler:2.2.1
    - name: run fastlane
      env:
        SLACK_URL: ${{ secrets.SLACK_WEBHOOK }}
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'stage'
        subdirectory: 'app'
        options: '{"auto_increment": true, "slack_url": "$SLACK_URL"}'
    - name: configure git
      run: |
        git config --global user.name 'github ci'
        git config --global user.email 'dev@dreipol.ch'
    - name: commit and push changes
      run: |
        git commit -am "Set new versionCode"
        git push origin HEAD:${{env.branch}}
    - name: create tag
      run: |
        versionCode=$(grep -o 'versionCode\s[0-9]*' ./app/build.gradle | tr -dc '0-9')
        tagname="android_$versionCode"
        git tag $tagname
        git push origin $tagname HEAD:${{env.branch}}
  iOS:
    if: contains(github.ref, 'ios_')
    runs-on: macos-latest
    env:
      branch: ${{ github.event.release.target_commitish }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add AppstoreConnect API Key
      env:
        ASC_API_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY_DREIPOL }}
      run: echo "$ASC_API_KEY" > ./iOS/Multiplatform\ Redux\ Sample/fastlane/appstoreConnect.json
    - name: Add .env File
      env: 
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      run: echo "${{ secrets.IOS_ENVVAR }}" > ./iOS/Multiplatform\ Redux\ Sample/fastlane/.env.secret
    - uses: actions/setup-ruby@v1
      with:
          ruby-version: '>= 2.6'
    - run: gem install bundler:2.2.1
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.FASTLANE_MATCH }}"
    - name: Run fastlane
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SLACK_URL: ${{ secrets.SLACK_WEBHOOK }}
      uses: maierj/fastlane-action@v2.0.0
      with:
        lane: 'stage'
        subdirectory: 'iOS/Multiplatform Redux Sample'
    - name: configure git
      run: |
        git config --global user.name 'github ci'
        git config --global user.email 'dev@dreipol.ch'
    - name: commit and push changes
      run: |
        git commit -am "Set new versionCode"
        git push origin HEAD:${{env.branch}}
    - name: create tag
      run: |
        versionCode=$(grep -o 'versionCode\s[0-9]*' ./app/build.gradle | tr -dc '0-9')
        tagname="android_$versionCode"
        git tag $tagname
        git push origin $tagname HEAD:${{env.branch}}
