name: Deploy Stage iOS CI

on:
  push:
    tags:
    - 'i[0-9]+'

jobs:
  iOS:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: todo
      run: echo TODO
    #TODO
    #https://github.com/marketplace/actions/fastlane-action
    #- name: run fastlane
      #uses: maierj/fastlane-action@v1.4.0
      #with:
        #lane: 'stage'
        #subdirectory: 'ios'
        #options: '{"auto_increment": false}'