name: Deploy Stage CI

on:
  push:
    #tags:
    #- '*'

jobs:
  android:
    if: contains(github.event.repository.branches_url, 'release/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run fastlane
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'stage'
        subdirectory: 'app'
        options: '{"auto_increment": false}'
  iOS:
    #if: contains(github.event.repository.branches_url, "release/")
    runs-on: macos-latest
    steps:
    - name: todo
      env:
        BRANCHE: ${GITHUB_REF#refs/*/}
      run: echo $BRANCHE
    #TODO
    #https://github.com/marketplace/actions/fastlane-action
    #- name: run fastlane
      #uses: maierj/fastlane-action@v1.4.0
      #with:
        #lane: 'stage'
        #subdirectory: 'ios'
        #options: '{"auto_increment": false}'