name: Deploy Stage CI

on:
  push:
    #tags:
    #- '*'

jobs:
  android:
    #if: contains(github.ref, "release/")
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: cache gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: run fastlane
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'stage'
        subdirectory: 'app'
        options: '{"auto_increment": false}'
  iOS:
    #if: contains(github.ref, "release/")
    runs-on: macos-latest
    steps:
    - name: todo
      run: echo "TODO"