name: Deploy Prod CI

on:
  pull_request:
    types: [closed]

jobs:
  android:
    if: github.event.pull_request.merged == 'true' && cotains(github.head_ref, 'release/android')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run fastlane
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: 'production'
        subdirectory: 'app'
        options: '{"auto_increment": false}'
  iOS:
    if: github.event.pull_request.merged == 'true' && cotains(github.head_ref, 'release/ios')
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: todo
      run: echo TODO
    #TODO
    #https://github.com/marketplace/actions/fastlane-action
    #- name: run fastlane
      #uses: maierj/fastlane-action@v1.4.0
      #with:
        #lane: 'production'
        #subdirectory: 'ios'
        #options: '{"auto_increment": false}'