# This is a basic workflow to help you get started with Actions

name: Test match repo

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run SSH test
        env: 
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.FASTLANE_MATCH }}
        run: ssh-agent bash -c 'ssh-add - <<< $MATCH_GIT_PRIVATE_KEY; git clone git@github.com:dreipol/fastlane-certificates.git /tmp/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20210112-6752-iw0m2l -b dreipol --single-branch'
